import { describe, it, expect } from 'vitest';
import { parse } from '../../src/markdown/parse';
import { serialize } from '../../src/markdown/serialize';
import { loadCorpus } from './runner';

const corpus = loadCorpus();

describe('Markdown round-trip corpus (FR-005, SC-003)', () => {
  it('loads at least one fixture', () => {
    expect(corpus.length).toBeGreaterThan(0);
  });

  for (const c of corpus) {
    describe(c.name, () => {
      it('serialization is deterministic (stable markers)', () => {
        const once = serialize(parse(c.input));
        const twice = serialize(parse(c.input));
        expect(twice).toBe(once);
      });

      it('round-trip is idempotent (lossless re-parse)', () => {
        const first = serialize(parse(c.input));
        const second = serialize(parse(first));
        expect(second).toBe(first);
      });

      it('matches the committed golden expected output', () => {
        // Expected files are generated by `node scripts/generate-corpus.mjs`.
        if (c.expected == null) {
          throw new Error(`Missing expected golden file for ${c.name}`);
        }
        expect(serialize(parse(c.input))).toBe(c.expected);
      });

      it('produces standards-only output (no proprietary markers)', () => {
        const out = serialize(parse(c.input));
        expect(out).not.toMatch(/data-pm-|<pm:/);
        expect(out.includes('\u0000')).toBe(false);
      });
    });
  }
});
